
export enum Marca {
  Bosh = "BOSH",
  Boyl = "BOYL",
  Castrol = "CASTROL",
  Deluxe = "DELUXE",
  Gulf = "GULF",
  Hyunday = "HYUNDAY",
  Kraft = "KRAFT",
  LiquiMoly = "LIQUI-MOLY",
  Lyz = "LYZ",
  Mobil = "MOBIL",
  Otro = "OTRO",
  Peak = "PEAK",
  Phillips66 = "PHILLIPS 66",
  Prestone = "PRESTONE",
  Purolator = "PUROLATOR",
  Sakura = "SAKURA",
  Shell = "SHELL",
  Valvoline = "VALVOLINE",
  Vistony = "VISTONY",
  WillyBush = "WILLY BUSH",
}
